### ISSUE TITLE
Weapon Paints doesnt' work on aim_map, $2000, etc.

### ISSUE THREAD

**Issue by marcin016** [Franc1sco/Franug-Weapon_Paints#14]
Hello
I have a problem with this plugin.
Paint does not work on maps like aim_map, $ 2,000
On these maps, raises the standard weapons (AK-47, M4A4) and there is no paint.
On normal maps de_dust, de_cache everything is OK.

**Comment by joao-mambelli** [comment]
because these maps has weapons apawn on ground, they aren't yours, then there is no way to apply the paints on these weapons when they spawn. like, how the plugin will know which player will take that weapon...
this plugin will work on weapons that are setted with:
"mp_ct_default_primary" (e.g.: mp_ct_default_primary "weapon_m4a1")
"mp_ct_default_secondary" (e.g.: mp_ct_default_secondary "weapon_hkp2000")
"mp_t_default_primary" (e.g.: mp_t_default_primary "weapon_ak47")
"mp_t_default_secondary" (e.g.: mp_t_default_primary "weapon_glock")

or if they are purchased with buy menu.

**Comment by marcin016** [comment]
I had previously weapon paints v1.6.4 plugin.
And this plugin works on maps like aim_map etc.

**Comment by Franc1sco** [comment]
Then use something like "always wepon skins" plugin if you want to apply skins in weapons in the map.
